// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config/v1/security.proto

package configv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AuthNConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuthNConfigMultiError, or
// nil if none found.
func (m *AuthNConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Disabled

	if _, ok := _AuthNConfig_Type_InLookup[m.GetType()]; !ok {
		err := AuthNConfigValidationError{
			field:  "Type",
			reason: "value must be in list [noop jwt oidc pre_shared_key basic_auth oauth2 ldap x509 saml api_key]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetJwt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthNConfigValidationError{
					field:  "Jwt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthNConfigValidationError{
					field:  "Jwt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJwt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthNConfigValidationError{
				field:  "Jwt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOidc()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthNConfigValidationError{
					field:  "Oidc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthNConfigValidationError{
					field:  "Oidc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOidc()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthNConfigValidationError{
				field:  "Oidc",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPreSharedKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthNConfigValidationError{
					field:  "PreSharedKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthNConfigValidationError{
					field:  "PreSharedKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPreSharedKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthNConfigValidationError{
				field:  "PreSharedKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AuthNConfigMultiError(errors)
	}

	return nil
}

// AuthNConfigMultiError is an error wrapping multiple validation errors
// returned by AuthNConfig.ValidateAll() if the designated constraints aren't met.
type AuthNConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfigMultiError) AllErrors() []error { return m }

// AuthNConfigValidationError is the validation error returned by
// AuthNConfig.Validate if the designated constraints aren't met.
type AuthNConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfigValidationError) ErrorName() string { return "AuthNConfigValidationError" }

// Error satisfies the builtin error interface
func (e AuthNConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfigValidationError{}

var _AuthNConfig_Type_InLookup = map[string]struct{}{
	"noop":           {},
	"jwt":            {},
	"oidc":           {},
	"pre_shared_key": {},
	"basic_auth":     {},
	"oauth2":         {},
	"ldap":           {},
	"x509":           {},
	"saml":           {},
	"api_key":        {},
}

// Validate checks the field values on AuthZConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthZConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthZConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuthZConfigMultiError, or
// nil if none found.
func (m *AuthZConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthZConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Disabled

	if _, ok := _AuthZConfig_Type_InLookup[m.GetType()]; !ok {
		err := AuthZConfigValidationError{
			field:  "Type",
			reason: "value must be in list [noop casbin opa zanzibar]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCasbin()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthZConfigValidationError{
					field:  "Casbin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthZConfigValidationError{
					field:  "Casbin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCasbin()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthZConfigValidationError{
				field:  "Casbin",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOpa()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthZConfigValidationError{
					field:  "Opa",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthZConfigValidationError{
					field:  "Opa",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOpa()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthZConfigValidationError{
				field:  "Opa",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetZanzibar()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthZConfigValidationError{
					field:  "Zanzibar",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthZConfigValidationError{
					field:  "Zanzibar",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetZanzibar()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthZConfigValidationError{
				field:  "Zanzibar",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AuthZConfigMultiError(errors)
	}

	return nil
}

// AuthZConfigMultiError is an error wrapping multiple validation errors
// returned by AuthZConfig.ValidateAll() if the designated constraints aren't met.
type AuthZConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthZConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthZConfigMultiError) AllErrors() []error { return m }

// AuthZConfigValidationError is the validation error returned by
// AuthZConfig.Validate if the designated constraints aren't met.
type AuthZConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthZConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthZConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthZConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthZConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthZConfigValidationError) ErrorName() string { return "AuthZConfigValidationError" }

// Error satisfies the builtin error interface
func (e AuthZConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthZConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthZConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthZConfigValidationError{}

var _AuthZConfig_Type_InLookup = map[string]struct{}{
	"noop":     {},
	"casbin":   {},
	"opa":      {},
	"zanzibar": {},
}

// Validate checks the field values on Security with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Security) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Security with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SecurityMultiError, or nil
// if none found.
func (m *Security) ValidateAll() error {
	return m.validate(true)
}

func (m *Security) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAuthz()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SecurityValidationError{
					field:  "Authz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SecurityValidationError{
					field:  "Authz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthz()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SecurityValidationError{
				field:  "Authz",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAuthn()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SecurityValidationError{
					field:  "Authn",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SecurityValidationError{
					field:  "Authn",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthn()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SecurityValidationError{
				field:  "Authn",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SecurityMultiError(errors)
	}

	return nil
}

// SecurityMultiError is an error wrapping multiple validation errors returned
// by Security.ValidateAll() if the designated constraints aren't met.
type SecurityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SecurityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SecurityMultiError) AllErrors() []error { return m }

// SecurityValidationError is the validation error returned by
// Security.Validate if the designated constraints aren't met.
type SecurityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SecurityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SecurityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SecurityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SecurityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SecurityValidationError) ErrorName() string { return "SecurityValidationError" }

// Error satisfies the builtin error interface
func (e SecurityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSecurity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SecurityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SecurityValidationError{}

// Validate checks the field values on AuthNConfig_JWTConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_JWTConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_JWTConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_JWTConfigMultiError, or nil if none found.
func (m *AuthNConfig_JWTConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_JWTConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Algorithm

	// no validation rules for SigningKey

	// no validation rules for OldSigningKey

	// no validation rules for ExpireTime

	// no validation rules for RefreshTime

	// no validation rules for CacheName

	if len(errors) > 0 {
		return AuthNConfig_JWTConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_JWTConfigMultiError is an error wrapping multiple validation
// errors returned by AuthNConfig_JWTConfig.ValidateAll() if the designated
// constraints aren't met.
type AuthNConfig_JWTConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_JWTConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_JWTConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_JWTConfigValidationError is the validation error returned by
// AuthNConfig_JWTConfig.Validate if the designated constraints aren't met.
type AuthNConfig_JWTConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_JWTConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_JWTConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_JWTConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_JWTConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_JWTConfigValidationError) ErrorName() string {
	return "AuthNConfig_JWTConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_JWTConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_JWTConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_JWTConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_JWTConfigValidationError{}

// Validate checks the field values on AuthNConfig_OIDCConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_OIDCConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_OIDCConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_OIDCConfigMultiError, or nil if none found.
func (m *AuthNConfig_OIDCConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_OIDCConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IssuerUrl

	// no validation rules for Audience

	// no validation rules for Algorithm

	if len(errors) > 0 {
		return AuthNConfig_OIDCConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_OIDCConfigMultiError is an error wrapping multiple validation
// errors returned by AuthNConfig_OIDCConfig.ValidateAll() if the designated
// constraints aren't met.
type AuthNConfig_OIDCConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_OIDCConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_OIDCConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_OIDCConfigValidationError is the validation error returned by
// AuthNConfig_OIDCConfig.Validate if the designated constraints aren't met.
type AuthNConfig_OIDCConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_OIDCConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_OIDCConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_OIDCConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_OIDCConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_OIDCConfigValidationError) ErrorName() string {
	return "AuthNConfig_OIDCConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_OIDCConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_OIDCConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_OIDCConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_OIDCConfigValidationError{}

// Validate checks the field values on AuthNConfig_PreSharedKeyConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_PreSharedKeyConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_PreSharedKeyConfig with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// AuthNConfig_PreSharedKeyConfigMultiError, or nil if none found.
func (m *AuthNConfig_PreSharedKeyConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_PreSharedKeyConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthNConfig_PreSharedKeyConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_PreSharedKeyConfigMultiError is an error wrapping multiple
// validation errors returned by AuthNConfig_PreSharedKeyConfig.ValidateAll()
// if the designated constraints aren't met.
type AuthNConfig_PreSharedKeyConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_PreSharedKeyConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_PreSharedKeyConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_PreSharedKeyConfigValidationError is the validation error
// returned by AuthNConfig_PreSharedKeyConfig.Validate if the designated
// constraints aren't met.
type AuthNConfig_PreSharedKeyConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_PreSharedKeyConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_PreSharedKeyConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_PreSharedKeyConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_PreSharedKeyConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_PreSharedKeyConfigValidationError) ErrorName() string {
	return "AuthNConfig_PreSharedKeyConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_PreSharedKeyConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_PreSharedKeyConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_PreSharedKeyConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_PreSharedKeyConfigValidationError{}

// Validate checks the field values on AuthNConfig_BasicAuthConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_BasicAuthConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_BasicAuthConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_BasicAuthConfigMultiError, or nil if none found.
func (m *AuthNConfig_BasicAuthConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_BasicAuthConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthNConfig_BasicAuthConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_BasicAuthConfigMultiError is an error wrapping multiple
// validation errors returned by AuthNConfig_BasicAuthConfig.ValidateAll() if
// the designated constraints aren't met.
type AuthNConfig_BasicAuthConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_BasicAuthConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_BasicAuthConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_BasicAuthConfigValidationError is the validation error returned
// by AuthNConfig_BasicAuthConfig.Validate if the designated constraints
// aren't met.
type AuthNConfig_BasicAuthConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_BasicAuthConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_BasicAuthConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_BasicAuthConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_BasicAuthConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_BasicAuthConfigValidationError) ErrorName() string {
	return "AuthNConfig_BasicAuthConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_BasicAuthConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_BasicAuthConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_BasicAuthConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_BasicAuthConfigValidationError{}

// Validate checks the field values on AuthNConfig_OAuth2Config with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_OAuth2Config) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_OAuth2Config with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_OAuth2ConfigMultiError, or nil if none found.
func (m *AuthNConfig_OAuth2Config) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_OAuth2Config) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthNConfig_OAuth2ConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_OAuth2ConfigMultiError is an error wrapping multiple validation
// errors returned by AuthNConfig_OAuth2Config.ValidateAll() if the designated
// constraints aren't met.
type AuthNConfig_OAuth2ConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_OAuth2ConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_OAuth2ConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_OAuth2ConfigValidationError is the validation error returned by
// AuthNConfig_OAuth2Config.Validate if the designated constraints aren't met.
type AuthNConfig_OAuth2ConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_OAuth2ConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_OAuth2ConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_OAuth2ConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_OAuth2ConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_OAuth2ConfigValidationError) ErrorName() string {
	return "AuthNConfig_OAuth2ConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_OAuth2ConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_OAuth2Config.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_OAuth2ConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_OAuth2ConfigValidationError{}

// Validate checks the field values on AuthNConfig_LdapConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_LdapConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_LdapConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_LdapConfigMultiError, or nil if none found.
func (m *AuthNConfig_LdapConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_LdapConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthNConfig_LdapConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_LdapConfigMultiError is an error wrapping multiple validation
// errors returned by AuthNConfig_LdapConfig.ValidateAll() if the designated
// constraints aren't met.
type AuthNConfig_LdapConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_LdapConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_LdapConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_LdapConfigValidationError is the validation error returned by
// AuthNConfig_LdapConfig.Validate if the designated constraints aren't met.
type AuthNConfig_LdapConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_LdapConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_LdapConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_LdapConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_LdapConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_LdapConfigValidationError) ErrorName() string {
	return "AuthNConfig_LdapConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_LdapConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_LdapConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_LdapConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_LdapConfigValidationError{}

// Validate checks the field values on AuthNConfig_X509Config with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_X509Config) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_X509Config with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_X509ConfigMultiError, or nil if none found.
func (m *AuthNConfig_X509Config) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_X509Config) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthNConfig_X509ConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_X509ConfigMultiError is an error wrapping multiple validation
// errors returned by AuthNConfig_X509Config.ValidateAll() if the designated
// constraints aren't met.
type AuthNConfig_X509ConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_X509ConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_X509ConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_X509ConfigValidationError is the validation error returned by
// AuthNConfig_X509Config.Validate if the designated constraints aren't met.
type AuthNConfig_X509ConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_X509ConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_X509ConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_X509ConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_X509ConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_X509ConfigValidationError) ErrorName() string {
	return "AuthNConfig_X509ConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_X509ConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_X509Config.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_X509ConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_X509ConfigValidationError{}

// Validate checks the field values on AuthNConfig_SamlConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_SamlConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_SamlConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_SamlConfigMultiError, or nil if none found.
func (m *AuthNConfig_SamlConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_SamlConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthNConfig_SamlConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_SamlConfigMultiError is an error wrapping multiple validation
// errors returned by AuthNConfig_SamlConfig.ValidateAll() if the designated
// constraints aren't met.
type AuthNConfig_SamlConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_SamlConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_SamlConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_SamlConfigValidationError is the validation error returned by
// AuthNConfig_SamlConfig.Validate if the designated constraints aren't met.
type AuthNConfig_SamlConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_SamlConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_SamlConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_SamlConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_SamlConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_SamlConfigValidationError) ErrorName() string {
	return "AuthNConfig_SamlConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_SamlConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_SamlConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_SamlConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_SamlConfigValidationError{}

// Validate checks the field values on AuthNConfig_ApiKeyConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthNConfig_ApiKeyConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthNConfig_ApiKeyConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthNConfig_ApiKeyConfigMultiError, or nil if none found.
func (m *AuthNConfig_ApiKeyConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthNConfig_ApiKeyConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthNConfig_ApiKeyConfigMultiError(errors)
	}

	return nil
}

// AuthNConfig_ApiKeyConfigMultiError is an error wrapping multiple validation
// errors returned by AuthNConfig_ApiKeyConfig.ValidateAll() if the designated
// constraints aren't met.
type AuthNConfig_ApiKeyConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNConfig_ApiKeyConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNConfig_ApiKeyConfigMultiError) AllErrors() []error { return m }

// AuthNConfig_ApiKeyConfigValidationError is the validation error returned by
// AuthNConfig_ApiKeyConfig.Validate if the designated constraints aren't met.
type AuthNConfig_ApiKeyConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNConfig_ApiKeyConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNConfig_ApiKeyConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNConfig_ApiKeyConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNConfig_ApiKeyConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNConfig_ApiKeyConfigValidationError) ErrorName() string {
	return "AuthNConfig_ApiKeyConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthNConfig_ApiKeyConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthNConfig_ApiKeyConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNConfig_ApiKeyConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNConfig_ApiKeyConfigValidationError{}

// Validate checks the field values on AuthZConfig_CasbinConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthZConfig_CasbinConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthZConfig_CasbinConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthZConfig_CasbinConfigMultiError, or nil if none found.
func (m *AuthZConfig_CasbinConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthZConfig_CasbinConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PolicyFile

	// no validation rules for ModelFile

	if len(errors) > 0 {
		return AuthZConfig_CasbinConfigMultiError(errors)
	}

	return nil
}

// AuthZConfig_CasbinConfigMultiError is an error wrapping multiple validation
// errors returned by AuthZConfig_CasbinConfig.ValidateAll() if the designated
// constraints aren't met.
type AuthZConfig_CasbinConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthZConfig_CasbinConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthZConfig_CasbinConfigMultiError) AllErrors() []error { return m }

// AuthZConfig_CasbinConfigValidationError is the validation error returned by
// AuthZConfig_CasbinConfig.Validate if the designated constraints aren't met.
type AuthZConfig_CasbinConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthZConfig_CasbinConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthZConfig_CasbinConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthZConfig_CasbinConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthZConfig_CasbinConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthZConfig_CasbinConfigValidationError) ErrorName() string {
	return "AuthZConfig_CasbinConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthZConfig_CasbinConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthZConfig_CasbinConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthZConfig_CasbinConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthZConfig_CasbinConfigValidationError{}

// Validate checks the field values on AuthZConfig_OpaConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthZConfig_OpaConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthZConfig_OpaConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthZConfig_OpaConfigMultiError, or nil if none found.
func (m *AuthZConfig_OpaConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthZConfig_OpaConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PolicyFile

	// no validation rules for DataFile

	// no validation rules for ServerUrl

	// no validation rules for RegoFile

	if len(errors) > 0 {
		return AuthZConfig_OpaConfigMultiError(errors)
	}

	return nil
}

// AuthZConfig_OpaConfigMultiError is an error wrapping multiple validation
// errors returned by AuthZConfig_OpaConfig.ValidateAll() if the designated
// constraints aren't met.
type AuthZConfig_OpaConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthZConfig_OpaConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthZConfig_OpaConfigMultiError) AllErrors() []error { return m }

// AuthZConfig_OpaConfigValidationError is the validation error returned by
// AuthZConfig_OpaConfig.Validate if the designated constraints aren't met.
type AuthZConfig_OpaConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthZConfig_OpaConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthZConfig_OpaConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthZConfig_OpaConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthZConfig_OpaConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthZConfig_OpaConfigValidationError) ErrorName() string {
	return "AuthZConfig_OpaConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthZConfig_OpaConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthZConfig_OpaConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthZConfig_OpaConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthZConfig_OpaConfigValidationError{}

// Validate checks the field values on AuthZConfig_ZanzibarConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthZConfig_ZanzibarConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthZConfig_ZanzibarConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthZConfig_ZanzibarConfigMultiError, or nil if none found.
func (m *AuthZConfig_ZanzibarConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthZConfig_ZanzibarConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApiEndpoint

	// no validation rules for Namespace

	// no validation rules for ReadConsistency

	// no validation rules for WriteConsistency

	if len(errors) > 0 {
		return AuthZConfig_ZanzibarConfigMultiError(errors)
	}

	return nil
}

// AuthZConfig_ZanzibarConfigMultiError is an error wrapping multiple
// validation errors returned by AuthZConfig_ZanzibarConfig.ValidateAll() if
// the designated constraints aren't met.
type AuthZConfig_ZanzibarConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthZConfig_ZanzibarConfigMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthZConfig_ZanzibarConfigMultiError) AllErrors() []error { return m }

// AuthZConfig_ZanzibarConfigValidationError is the validation error returned
// by AuthZConfig_ZanzibarConfig.Validate if the designated constraints aren't met.
type AuthZConfig_ZanzibarConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthZConfig_ZanzibarConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthZConfig_ZanzibarConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthZConfig_ZanzibarConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthZConfig_ZanzibarConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthZConfig_ZanzibarConfigValidationError) ErrorName() string {
	return "AuthZConfig_ZanzibarConfigValidationError"
}

// Error satisfies the builtin error interface
func (e AuthZConfig_ZanzibarConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthZConfig_ZanzibarConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthZConfig_ZanzibarConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthZConfig_ZanzibarConfigValidationError{}
